OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  # 1. Platform (운영사)
  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  # 2. Issuer (발행사)
  - Name: Org2
    Domain: org2.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  # 3. Custody (수탁사)
  - Name: Org3
    Domain: org3.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  # 4. Auditor (감사기관)
  - Name: Org4
    Domain: org4.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  # 5. Bank (정산은행)
  - Name: Org5
    Domain: org5.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1